@isTest
public class gcTest_Coverage {
	static testMethod void testMethod01()
	{
		gcCoverage.method01();
		gcCoverage.method02();
		gcCoverage.method03();
		gcCoverage.method04();
		gcCoverage.method05();
	}
	static testMethod void testMethod02()
	{
		gcCoverage.method06();
		gcCoverage.method07();
		gcCoverage.method08();
		gcCoverage.method09();
		gcCoverage.method10();
	}
	static testMethod void testMethod03()
	{
		gcCoverage.method11();
		gcCoverage.method12();
		gcCoverage.method13();
		gcCoverage.method14();	
	}
}